# Generated by Django 2.0.6 on 2018-08-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe_name', models.CharField(max_length=100)),
                ('original_gravity', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SGravity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('specific_gravity', models.DecimalField(decimal_places=3, max_digits=4)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gravity.Recipe')),
            ],
        ),
    ]
