# Generated by Django 2.0.6 on 2018-08-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gravity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sgravity',
            options={'verbose_name_plural': 'S Gravity'},
        ),
    ]
